### ISSUE TITLE
package removed from packagecontrol

### ISSUE THREAD

**Issue by Noiwex** [glua/SublimeLinter-contrib-glua#2]
what the fuck

**Comment by wiox** [comment]
Didn't realise this was under this organisation. Somebody will have to write to whoever manages package-control to explain that the organisation was renamed from "gmodcoders" to "glua".

**Comment by Noiwex** [comment]
lol haha

**Comment by HandsomeMatt** [comment]
https://packagecontrol.io/docs/renaming_a_package

**Comment by samuelmaddock** [comment]
For some reason I didn't get a notification about this, I'll look into fixing this soon. :(

**Comment by samuelmaddock** [comment]
Created a PR to fix this; you can track progress here: SublimeLinter/package_control_channel#22

**Comment by samuelmaddock** [comment]
Package should be available whenever the crawler next checks it.
